name: CD
on:
  push:
    branches: 
      - main
      - feature/github-actions

env:
  NAME_REPOSITORY: ${{ vars.NAME_REPOSITORY }}
jobs:
  updata_project:
    runs-on: ubuntu-latest
    steps:
      - name: Conected to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd "learn-fast-api" 
            git pull
            sudo systemctl stop learn-fast-api
            sudo systemctl daemon-reload
            sudo systemctl start learn-fast-api



      

  