name: First Workflow
on: [push]

jobs:
  run-first-comand: 
    runs-on: ubuntu-latest
    steps:
    - name: Display some Text
      run: echo "some text"
    - name: Comand 
      run: | 
        node -v
        npm -v
