name: First Workflow
on: [push]

jobs:
  run-first-comand: 
    runs-on: ubuntu-latest
    steps:
    - name: version node in ubunto
      run: | 
        node -v
  
  run-parolel-comand:
    runs-on: windows-latest
    steps:
      - name: version node in windows
        run: node -v

  run-second-comand: 
    runs-on: macos-latest
    needs: [run-first-comand]
    steps:
      - name: version node in macos
        run: node -v